#!/bin/bash -
# Copyright (C) 2016-2018 Red Hat Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

source config

# Catch some obvious problems.
if [ ! -d "$ROOT" ]; then
    echo "$0: config was not set, read the README"
    exit 1
fi
if [ "$(id -u)" -eq 0 ]; then
    echo "$0: don't run this script as root"
    exit 1
fi

while true; do
    busy=0
    # Number of current builds ongoing.
    nbuilds=`pidof cp qemu-system-riscv64 virt-customize | wc -w`
    if [ $nbuilds -lt $NR ]; then
        # Can start a new build, but which?
        srpm="$(find $ROOT/input -name '*.src.rpm' | sort -V | head -1)"
        if [ "x$srpm" != "x" ]; then
            echo "Starting build: $srpm"
            ./build $srpm &
            busy=1
        fi
    fi

    if [ "$busy" -eq 0 ]; then
        # Do we need to createrepo and push?
        if test -f $ROOT/needs-push; then
            rm -f $ROOT/needs-push
            echo "Creating repo and pushing to local web server"
            ./push
        fi

        # Do we need to upload to the public repo?
        if test -f $ROOT/needs-upload; then
            rm -f $ROOT/needs-upload
            echo "Uploading to the public web server"
            ./upload srpms rpms repodata
        fi
    fi

    ./upload logs status
    sleep $INTERVAL
done
