#!/bin/bash -
# Copyright (C) 2016-2018 Red Hat Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

source config

# Catch some obvious problems.
if [ ! -d "$ROOT" ]; then
    echo "$0: config was not set, read the README"
    exit 1
fi
if [ "$(id -u)" -eq 0 ]; then
    echo "$0: don't run this script as root"
    exit 1
fi

while true; do
    # Number of current builds ongoing.
    # Can remove 'dnf' here when we get rid of tdnf.
    nbuilds=`pidof cp python3 qemu-system-riscv64 | wc -w`
    if [ $nbuilds -lt $NR ]; then
        # Can start a new build, but which?
        srpm="$(find $ROOT/input -name '*.src.rpm' | sort -V | head -1)"
        if [ "x$srpm" != "x" ]; then
            echo "Starting build: $srpm"
            ./build $srpm &
        fi
    fi
    sleep $INTERVAL
done
