#!/bin/bash -
# Copyright (C) 2016-2018 Red Hat Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

source config

set -e

# Run one build.

srpm="$1"
basename="$(basename $1)"
name="$(rpm -q --qf '%{NAME}\n' -p $srpm)"

# Log files go here.
mkdir -p $ROOT/logs/$basename
exec >& $ROOT/logs/$basename/script.log

result ()
{
    echo "$@" >> $ROOT/autobuild-status.html

    # Try to rsync with the main webserver, don't fail if we can't.
    pushd $ROOT
    rsync -av SRPMS fedorapeople.org:/project/risc-v/ ||:
    rsync -av RPMS/noarch fedorapeople.org:/project/risc-v/RPMS/ ||:
    rsync -av RPMS/riscv64 fedorapeople.org:/project/risc-v/RPMS/ ||:
    rsync -av logs fedorapeople.org:/project/risc-v/ ||:
    rsync -av autobuild-status.html fedorapeople.org:/project/risc-v/ ||:
    popd
}

# Create a temporary directory for the build, and ensure it is always
# cleaned up after.
tmpdir="$(mktemp -d $ROOT/tmp/$name.XXXXXX)"
cleanup ()
{
    r=$?
    rm -rf $tmpdir ||:
    exit $r
}
trap cleanup INT QUIT TERM EXIT ERR

# Move the SRPM into tmpdir.  Also prevents it from being picked up
# again by the autobuild script.
mv $srpm $tmpdir/

# Short-circuit noarch RPMs.  We can just download them.
pushd $tmpdir
if rpm -qip "$basename" | grep -sq '^Architecture: noarch$'; then
    koji download-build `echo "$basename" | sed s/.src.rpm//`
    mv *.noarch.rpm $ROOT/RPMS/noarch/
    mv *.src.rpm $ROOT/SRPMS/
    exit 0
fi
popd

# Copy stage4-disk.img and rpms-disk.img into the tmpdir.
cp $ROOT/stage4-disk.img $tmpdir/$name-disk.img
cp $ROOT/rpms-disk.img $tmpdir/$name-rpms-disk.img

# Copy the init file and modify it.
sed -e "s,@SRPM@,$basename,g" < init.in > $tmpdir/$name-init.sh

# Copy in the init script and SRPM.
guestfish -a $tmpdir/$name-disk.img -i <<EOF
    upload $tmpdir/$name-init.sh /init
    chmod 0755 /init
    upload $tmpdir/$basename /var/tmp/$basename
EOF

# Boot first time to set up the root.
qemu-system-riscv64 \
    -nographic -machine virt -m 2G \
    -kernel $ROOT/bbl \
    -append "console=ttyS0 ro root=/dev/vda init=/init" \
    -drive file=$tmpdir/$name-disk.img,format=raw,if=none,id=hd0 \
    -device virtio-blk-device,drive=hd0 \
    -drive file=$tmpdir/$name-rpms-disk.img,format=raw,if=none,id=hd1 \
    -device virtio-blk-device,drive=hd1 \
    -device virtio-net-device,netdev=usernet \
    -netdev user,id=usernet >& $ROOT/logs/$basename/root.log

# Did the root get set up correctly?
if ! guestfish --ro -a $tmpdir/$name-disk.img -i stat /rootok; then
    result "<span style='color:red;'><b>FAIL</b></span>: $basename <a href=logs/$basename/root.log>root.log</a> <br/>"
    exit 1
fi

# Boot second time to perform the build.
qemu-system-riscv64 \
    -nographic -machine virt -m 2G \
    -kernel $ROOT/bbl \
    -append "console=ttyS0 ro root=/dev/vda init=/init" \
    -drive file=$tmpdir/$name-disk.img,format=raw,if=none,id=hd0 \
    -device virtio-blk-device,drive=hd0 \
    -drive file=$tmpdir/$name-rpms-disk.img,format=raw,if=none,id=hd1 \
    -device virtio-blk-device,drive=hd1 \
    -device virtio-net-device,netdev=usernet \
    -netdev user,id=usernet >& $ROOT/logs/$basename/build.log

# Did the build work?
if ! guestfish --ro -a $tmpdir/$name-disk.img -i stat /buildok; then
    result "<span style='color:red;'><b>FAIL</b></span>: $basename <a href=logs/$basename/root.log>root.log</a> <a href=logs/$basename/build.log>build.log</a> <br/>"
    exit 1
fi

# If successful, copy out the generated RPMs.
cp $tmpdir/$basename $ROOT/SRPMS/
virt-copy-out -a $tmpdir/$name-disk.img /rpmbuild $tmpdir/
cp $tmpdir/rpmbuild/RPMS/noarch/*.noarch.rpm $ROOT/RPMS/noarch/ ||:
cp $tmpdir/rpmbuild/RPMS/riscv64/*.riscv64.rpm $ROOT/RPMS/riscv64/ ||:

result "<span style='color:green;'><b>SUCCESS:</b></span> $basename <a href=logs/$basename/root.log>root.log</a> <a href=logs/$basename/build.log>build.log</a> <br/>"

# Now we need to regenerate the RPMs disk, but don't fail if
# we can't do that.
pushd $ROOT
if virt-make-fs RPMS $tmpdir/rpms-disk.img.new -t ext2 -F raw; then
    rm rpms-disk.img
    mv $tmpdir/rpms-disk.img.new rpms-disk.img
fi
popd
