#!/bin/bash -
# Copyright (C) 2016-2018 Red Hat Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

source config

# Rebuild the repository and push everything to the local web server.

w="$(pwd)"

lockfile $ROOT/lock
pushd $ROOT >/dev/null

# Recreate the repodata.
pushd $ROOT/RPMS >/dev/null
createrepo_c -q -g "$w/comps-f28.xml" .
popd >/dev/null

# Upload the new set of RPMs and repodata to the web server.
rsync -a --delete $ROOT/RPMS $WEBSYNC

popd >/dev/null
rm -f $ROOT/lock
