#!/bin/bash -
# Copyright (C) 2016-2018 Red Hat Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

source config

# Try to rsync with the main webserver, don't fail if we can't.

lockfile $ROOT/lock
pushd $ROOT >/dev/null

for f in "$@"; do
    case "$f" in
        srpms)
            rsync -a SRPMS fedorapeople.org:/project/risc-v/ ||:
            ;;
        rpms)
            rsync -a RPMS/noarch fedorapeople.org:/project/risc-v/RPMS/ ||:
            rsync -a RPMS/riscv64 fedorapeople.org:/project/risc-v/RPMS/ ||:
            ;;
        repodata)
            rsync -a --delete RPMS/repodata fedorapeople.org:/project/risc-v/RPMS/ ||:
            ;;
        logs)
            rsync -a logs fedorapeople.org:/project/risc-v/ ||:
            ;;
        status)
            rsync -a autobuild-status.html fedorapeople.org:/project/risc-v/ ||:
            ;;
    esac
done

popd >/dev/null
rm -f $ROOT/lock
